site_name: "Using Windows as a client for HPC systems"
site_url: https://klust.github.io/windows-client-HPC
site_dir: "site/windows-client-HPC"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - content.code.copy
    - toc.follow
  palette:
    - primary: black

nav:
  - Home: index.md
  - Introduction: 0_00_introduction.md
  - Protocols and technologies:
    - 1_ProtocolsTechnologies/index.md
    - SSH: 1_ProtocolsTechnologies/1_01_SSH.md
    - Remote graphics: 1_ProtocolsTechnologies/1_02_Remote_graphics.md
    - Globus and GridFTP for file transfer: 1_ProtocolsTechnologies/1_03_Globus.md
  - Creating a Linux-like environment on Windows:
    - 2_LinuxOnWin/index.md
    - WSL and WSL2: 2_LinuxOnWin/2_01_WSL.md
    - CygWin: 2_LinuxOnWin/2_02_CygWin.md
  - Software:
    - 3_Software/index.md
    - All-in-one: 3_Software/3_01_allInOne.md
    - CLI via SSH: 3_Software/3_02_CLI_SSH.md
    - SFTP file transfer: 3_Software/3_03_SFTP.md
    - SSHFS file access: 3_Software/3_04_SSHFS.md
    - X server: 3_Software/3_05_Xserver.md
    - VNC clients: 3_Software/3_06_VNC.md
    - NX clients: 3_Software/3_07_NX.md
  - Cluster software stack on Windows: 
    - 4_Cluster_Stack/index.md
    - EESSI: 4_Cluster_Stack/4_01_EESSI.md
    - EasyBuild: 4_Cluster_Stack/4_02_EasyBuild.md
    - Spack: 4_Cluster_Stack/4_03_Spack.md
  - Issues:
    - 5_Issues/index.md
    - SSH key management: 5_Issues/5_01_SSH_key_management.md
    - Connecting to an X server in the Windows process space: 5_Issues/5_02_Connecting_WinX.md
    - Securing an X server in the Windows process space: 5_Issues/5_03_SecureX.md
    - Mapping users and groups between the Windows and WSL space: 5_Issues/5_04_Mapping_users.md
    - Upgrading Linux in WSL: 5_Issues/5_05_Upgrading_Linux.md
  - "App. A: Management":
    - A_Management_tips/index.md
    - openSUSE on WSL2: A_Management_tips/A_01_openSUSE.md
    - Fedora Remix on WSL2: A_Management_tips/A_02_Fedora_Remix.md
    - Ubuntu on WSL2: A_Management_tips/A_03_Ubuntu.md


plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search

markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  # add links in bottom right
  social:
    #- type: github
    #  icon: octicons/logo-github
    #  link: https://github.com/klust
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3szWMS7glcfWsEZTZXQ1oQ
